version: '3'

services:
  mongo_database:
    image: mongo
    container_name: mongo_db_container
    restart: always
    env_file:
      docker-compose.env
    ports:
      - '27017:27017'
    volumes:
      - ${PWD}/mongodb_data:/var/lib/mongodb/data
